// Auto-generated favorites list
// Multi-user support - each user has their own favorites
// Updated: 2026-01-25 21:13:16 UTC

export const favorites = {
  "918031124": ["pork-soda", "another-love", "promise", "like-him", "stick-season"],
  "53462190": ["another-love"],
  "919705100": ["kid-cudi", "married-life", "be-nice-2-me"],
  "915931217": ["golden-hour"],
  "691546047": ["pork-soda", "the-place-where-it-rained"],
  "347604851": ["hype-boy", "call-of-silence", "guren-no-yumiya", "red-swan", "akuma-no-ko", "shinzo-wo-sasageyo"],
  "845436524": ["stick-season", "song-of-storms", "resonanse-heavens-secret-requiem", "five-nights-at-freddys-movie", "passionfruit", "one", "get-jinxed", "impostor-syndrome"],
  "708988738": ["unravel", "bling-bang-bang-born", "gurenge"],
  "228438939": ["lonely-andreas-ronnberg"],
  "99737190": ["aria-math"],
  "55237855": ["grandmas-home", "bling-bang-bang-born"],
  "3154050": ["hype-boy"],
  "312094594": ["all-girls-are-the-same"],
  "434501082": ["among-us-drip", "bling-bang-bang-born", "unravel"],
  "483121752": ["rush-e", "megalovania"],
  "647586060": ["im-still-standing", "interstellar"],
  "346292950": ["bella-ciao", "final-duet", "mr-brightside"],
  "716469918": ["aria-math", "silhouette", "birds-of-a-feather", "memoria-aira", "song-of-storms", "the-cruel-angels-thesis", "kill-bill", "im-still-standing", "super-mario-bros-theme", "hope-xxxtentacion", "no-surprises-radiohead", "children-vinland-saga-edit", "rush-e", "spring-the-four-seasons"],
  "908083145": ["never-meant-to-belong", "megalovania", "i-love-abigail-but-she-dont-love-me-back", "oscillation-naktigonis", "if-looks-could-kill", "miku", "creep", "august-10", "notion", "the-world-death-note-op", "house-of-memories", "i-have-nothing", "in-the-pool", "like-him"],
  "555082251": ["its-been-so-long"],
  "924095686": ["five-nights-at-freddys-movie"],
  "898357634": ["chamber-of-reflection", "i-wanna-be-yours"],
  "827106398": ["fall-from-the-sky-pt-2", "treehouse-alex-g"],
  "862113733": ["all-girls-are-the-same", "the-world-death-note-op", "cigarettes-out-the-window", "resonanse-heavens-secret-requiem", "i-love-abigail-but-she-dont-love-me-back", "great-fairy-fountain", "its-raining-somewhere-else", "lost-woods", "red-swan", "never-meant-to-belong", "its-going-down-now", "otouto-mitai-na-sonzai"],
  "3236387": ["song-of-storms", "sad-song-we-the-kings", "pure-vessel", "no-surprises-radiohead", "great-fairy-fountain", "lost-woods", "bella-ciao", "debito-di-sonno", "unravel"],
  "153265370": ["pork-soda", "resonanse-heavens-secret-requiem"],
  "325166567": ["grandmas-home"],
  "96760961": ["if-i-am-with-you", "remember-me-from-coco", "my-way", "akaza-love-theme"],
  "865358404": ["no-surprises-radiohead", "i-love-abigail-but-she-dont-love-me-back", "spring-the-four-seasons", "kill-bill", "chamber-of-reflection", "fluxxwave", "como-la-flor", "passionfruit", "new-computers", "this-is-what-heartbreak-feels-like"],
  "2629288": ["song-of-storms", "five-nights-at-freddys-movie", "runaway"],
  "147008475": ["ready-or-not-c00lkidd", "creation-of-hatred", "famine", "grandmas-home"],
  "585801304": ["among-us-drip"],
  "650934596": ["runaway", "rush-e", "interstellar"],
  "386500934": ["tek-it"],
  "693562444": ["song-of-storms", "made-you-look"],
  "985966541": ["just-monika", "love-story-indila", "see-you-again-tyler-the-creator", "bella-ciao", "the-spectre", "alone-marshmello", "its-going-down-now", "megalovania", "bubblegum-kk", "master-of-puppets", "all-star", "bumble-bee", "glimpse-of-us", "minecraft-sweden", "order-heaven-pierce-her", "symphony-no-5", "super-mario-bros-theme", "spear-of-justice", "interstellar", "cupid", "slow-dancing-in-the-dark", "creep", "horizon", "faded", "silhouette", "skyfall", "howls-moving-castle-theme", "fur-elise", "door", "clair-de-lune", "golden-hour", "let-her-go", "orange"],
  "590886039": ["todos-black-flash"],
  "785872121": ["bumble-bee", "ode-to-joy", "never-meant-to-belong", "summer-the-four-seasons", "stick-season", "river-flows-in-you", "my-way", "my-love-mine-all-mine"],
  "886051397": ["thick-of-it", "rush-e", "another-love", "river-flows-in-you", "human-ragnbone-man", "robbery-juice-wrld", "stick-season"],
  "536548320": ["all-my-fellas", "fluxxwave", "black-hole-sun", "hidden-in-the-sand"],
  "346738910": ["song-of-storms", "interstellar", "grandmas-home", "love-story-indila"],
  "379523811": ["resonanse-heavens-secret-requiem"],
  "249704701": ["grandmas-home"],
  "915471213": ["creation-of-hatred"],
  "480372024": ["love-like-you", "another-love"],
  "211970397": ["tpot-intro-theme"],
  "928529978": ["grandmas-home"],
  "654047315": ["song-of-storms"],
  "67493169": ["love-like-you"],
  "191502156": ["runaway"]
};
